### PR TITLE
Added MEE6 Leveling Plugin

### PR DESCRIPTION
**Pull request by kpodp0ra**
Message, which is a reference to a recent action by the mee6 company, which was sending unwanted ads on DM asking users to vote for them on top.gg.

### CODE REVIEW

**Comment by tvhsin** [comment]
No way you actually PRed it💀💀

**Comment by tvhsin** [comment]
I thought you were jk lmao

**Review by tvhsin — APPROVED** [review]
LGTM👍

**Comment by Assassin-1234** [comment]
LGTM. thank you for this feature.

**Pull request merged**
